\ProvidesClass{HMA}[2023/08/10 v 0.1 Thesis Templates]

\LoadClass[open=right,  % Kapitel darf nur auf rechten Seite beginnen
paper=a4,               % DIN-A4-Papier
fontsize=11pt,          % Schriftgöße
headings=small,         % Kleine Überschriften
headsepline=true,       % Trennlinie am Kopf der Seite
footsepline=false,      % Keine Trennlinie am Fuß der Seite
bibliography=totoc,     % Literaturverzeichnis in das Inhaltsverzeichnis aufnehmen
DIV=7,                  % Verhältnis der Ränder zum bedruckten Bereich
chapterprefix=true,     % Kapitel x vor dem Kapitelnamen
cleardoublepage=plain,
numbers=noenddot 		% Keine Endpunkte bei der Überschriftennummerierung
]{scrbook}



