This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (10 entries accepted, 0 rejected).
Sorting entries....done (32 comparisons).
Generating output file thesis.acr....done (18 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
